title: Pyscado site
author:
  name: Pyscado

description: >
  This site is a place for me to upload write ups and projects related to
  malware development and reverse engineering.

#theme: minima

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

#header_pages:
#  - about.md

minima:
  skin: auto
